### ISSUE TITLE
iOS simulator cannot connect to app in dev

### ISSUE THREAD

**Issue by mayel** [liveview-native/live_view_native#107]
Xcode logs: `nw_socket_handle_socket_event [C1.1.1:2] Socket SO_ERROR [61: Connection refused]`
Simulator shows:
<img width="304" alt="Screenshot 2023-12-17 at 15 04 25" src="https://github.com/liveview-native/live_view_native/assets/115318/e3d9b906-f911-4663-931a-734d1fcc83a4">

Can see in the Elixir logs that the SWIFTUI code in LiveView is being rendered, and when going to http://localhost:4000/?_lvn[format]=swiftui everything looks right (which we can also connect to in the Simulator Safari):
```
<div data-phx-main data-phx-session="SFMyNTY.g2gDaAJhBXQAAAAIdwJpZG0AAAAUcGh4LUY2R21tLWVYcG9tUFF3NGx3BHZpZXd3G0VsaXhpci5Cb25maXJlLldlYi5Ib21lTGl2ZXcHc2Vzc2lvbnQAAAAAdwpwYXJlbnRfcGlkdwNuaWx3BnJvdXRlcncZRWxpeGlyLkJvbmZpcmUuV2ViLlJvdXRlcncJcm9vdF92aWV3dxtFbGl4aXIuQm9uZmlyZS5XZWIuSG9tZUxpdmV3CHJvb3RfcGlkdwNuaWx3DGxpdmVfc2Vzc2lvbmgCdwdkZWZhdWx0bggARkPampumoRduBgDaaEx4jAFiAAFRgA.pkd0QIYSPSdCioTV3kRgmtty0HeS14oxVJtkJxlNPSY" data-phx-static="SFMyNTY.g2gDaAJhBXQAAAADdwJpZG0AAAAUcGh4LUY2R21tLWVYcG9tUFF3NGx3CmFzc2lnbl9uZXdsAAAAAXcLX19jb250ZXh0X19qdwVmbGFzaHQAAAAAbgYA2mhMeIwBYgABUYA.10zqLhNpRu7cgOPQINFUPsajHfX40fLj4aqyAl6FUfI" id="phx-F6Gmm-eXpomPQw4l"><VStack>
  <compiled-lvn-stylesheet body="%{}"><VStack>


  <Text>
    Hello native 0.2 :)
  </Text>

</VStack>
</compiled-lvn-stylesheet>
</VStack></div>

**Comment by bcardarella** [comment]
@mayel thank you, can you run this command so we can see all of the response headers:

```
> curl 'http://localhost:4000/?_lvn\[format\]=swiftui' --verbose
```

**Comment by mayel** [comment]
```
< HTTP/1.1 200 OK
< date: Sun, 17 Dec 2023 15:15:52 GMT
< content-length: 862
< vary: accept-encoding
< content-type: text/html; charset=utf-8
< cache-control: max-age=0, private, must-revalidate
< x-request-id: F6GnXA5ukliA3cEAAsCh
< referrer-policy: strict-origin-when-cross-origin
< x-content-type-options: nosniff
< x-download-options: noopen
< x-frame-options: SAMEORIGIN
< x-permitted-cross-domain-policies: none
<
<div data-phx-main data-phx-session="SFMyNTY.g2gDaAJhBXQAAAAIdwJpZG0AAAAUcGh4LUY2R25YUzY5SEliZHdTQkd3BHZpZXd3G0VsaXhpci5Cb25maXJlLldlYi5Ib21lTGl2ZXcHc2Vzc2lvbnQAAAAAdwpwYXJlbnRfcGlkdwNuaWx3BnJvdXRlcncZRWxpeGlyLkJvbmZpcmUuV2ViLlJvdXRlcncJcm9vdF92aWV3dxtFbGl4aXIuQm9uZmlyZS5XZWIuSG9tZUxpdmV3CHJvb3RfcGlkdwNuaWx3DGxpdmVfc2Vzc2lvbmgCdwdkZWZhdWx0bggAOwJc5lynoRduBgB2E1l4jAFiAAFRgA.MN8FjOzYN1fjkwCouGe0IxD-zbi9K4zN4_KCJe6ihAc" data-phx-static="SFMyNTY.g2gDaAJhBXQAAAADdwJpZG0AAAAUcGh4LUY2R25YUzY5SEliZHdTQkd3CmFzc2lnbl9uZXdsAAAAAXcLX19jb250ZXh0X19qdwVmbGFzaHQAAAAAbgYAdhNZeIwBYgABUYA.URT4RdWSNYqgalNnohNtSkNT9Cq_z80UZP4MEaQ7sfI" id="phx-F6GnXS69HIbdwSBG"><VStack>
  <compiled-lvn-stylesheet body="%{}"><VStack>


      <Image name="bonfire-icon"></Image>


  <Text>
    Hello Bonfire native beta 2!
  </Text>

</VStack>
</compiled-lvn-stylesheet>
* Connection #0 to host localhost left intact
</VStack></div>%

**Comment by bcardarella** [comment]
oh you know what I don't see the `csrf` token in there.  Can you try to add this to your swiftui template:

```
<csrf-token value={get_csrf_token()} />
```

**Comment by mayel** [comment]
ah yeah because that's usually part of the layout (currently disabled here) 🤞

**Comment by mayel** [comment]
that was it! 
<img width="440" alt="Screenshot 2023-12-17 at 15 24 23" src="https://github.com/liveview-native/live_view_native/assets/115318/c0b9f683-7416-4b8c-a7d8-c797eba9b752">

**Comment by bcardarella** [comment]
@carson-katri can we improve the error message to indicate in the log when something is missing. In this case @mayel removed the layout as his app is an Umbrella and migrating from an older version of Phonenix. It is updated but there is still something missing on the layout stuff so we disabled them for now, which meant the `csrf_token` was gone but the error log in xcode didn't indicate this

**Comment by mayel** [comment]
resolved related issue in https://github.com/liveview-native/live_view_native/pull/108
