### ISSUE TITLE
List values are concatenated instead of encoded

### ISSUE THREAD

**Issue by carson-katri** [liveview-native/live_view_native#134]
When passing a `List` to an attribute, the values are not JSON encoded, but merged into a single string:

```elixir
selection = []
```
```heex
<List selection={@selection}>
```
This results in:
```html
<List selection="">
```
Expected:
```html
<List selection="[]">
```

When the list has values

```elixir
selection = ["1", "2"]
```
```heex
<List selection={@selection}>
```
This results in:
```html
<List selection="12">
```
Expected:
```html
<List selection='["1", "2"]'>
```

**Comment by bcardarella** [comment]
Can you confirm if this is true with `main`? I just tried to reproduce and cannot.

Also, FWIW the 2nd example should encode as:

```heex
<List selection="[\"1\",\"2\"]"></List>
```

**Comment by carson-katri** [comment]
Using `main` of `live_view_native` and `liveview_client_swiftui` I still get:
```html
<List selection="12">
</List>
```

**Comment by bcardarella** [comment]
This was a result of the consuming app having an overridden `phoenix_live_view` dependency that didn't include the upstream changes necessary to enable our special attribute handling. Once the next version of `phoenix_live_view` is cut we can remove the git refs and this will hopefully not be an issue again
