### ISSUE TITLE
Custom Modifier isn't found by server in `style` tag.

### ISSUE THREAD

**Issue by BrooklinJazz** [liveview-native/live_view_native#184]
@carson-katri and I defined a custom modifier called `markdownTheme` for a wrapper around the swift-markdown-ui library.

It doesn't seem to appear in the stylesheet when applied through the `style` attribute, but it does appear in a class.

This doesn't work:

```elixir
<Markdown style="markdownTheme(.gitHub)" baseURL="https://google.com">
```

But this does:

```elixir
~SHEET"""
"my-style" do
  markdownTheme(.gitHub)
end
"""

<Markdown style="markdownTheme(.gitHub)" class="my-style" baseURL="https://google.com">
```

The stylesheet output file is empty when using the `style` attribute. But contains the following when using `class` and a stylesheet:

```elixir
%{"my-style" => [{:markdownTheme, [], [{:., [], [nil, :gitHub]}]}]}
```

**Comment by bcardarella** [comment]
Is this still valid?

**Comment by bcardarella** [comment]
I suspect this is no longer valid, closing
