### ISSUE TITLE
problem solved | xcode build failed ：Command PhaseScriptExecution failed with a nonzero exit code 

### ISSUE THREAD

**Issue by youfun** [liveview-native/live_view_native#203]
problem solved （ try to update xcode and create a new project）
-----

mix phx.new hello_native --database sqlite3
cd hello_native 

add context in the mix.exs file.

 
```elixir
{:live_view_native, "~> 0.3.0"},
{:live_view_native_stylesheet, "~> 0.3.0"},
{:live_view_native_swiftui, "~> 0.3.0"},
{:live_view_native_live_form, "~> 0.3.0"}
``` 

 
mix deps.get

mix lvn.setup
 mix lvn.setup.config
mix lvn.setup.gen

run mix phx.server everything is work

open the xcode to build this project , it reported failed and error：

```

Showing Recent Messages
Error: You don’t have permission to save the file “BuiltinRegistry+Views.swift” in the folder “BuiltinRegistryGeneratorPlugin”.
 Command PhaseScriptExecution failed with a nonzero exit code 

```

**Comment by youfun** [comment]
when i try to run a SwiftUI demo ，it work. so maybe the xcode is working

**Comment by bcardarella** [comment]
@youfun I'll close but can you provide any insight on how this was resolved?

**Comment by youfun** [comment]
> try to update xcode and create a new project

I updated Xcode and made a new project, then it all started working. Probably the settings in my old Xcode were causing the problem.If you have a weird problem, restarting or reinstalling something new can usually fix it.
