### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by bcardarella** [liveview-native/live_view_native#27]
This can serve as an epic for now, but @BrooklinJazz has been playing around with what testing can look like in LVN.

We can leverage the pre-existing LV test functions, but adding some convenience functions for setting the `platform_id` as well setting the specific target (i.e. `watchos`, `macos`, etc...) will be great to have.

**Comment by bcardarella** [comment]
We'll want to settle on #28 before implementing the target helper

**Comment by BrooklinJazz** [comment]
With tremendous inspiration from Paulo Valente I drafted a working version. Open to feedback.

```elixir
defmodule LiveViewNative.Test do
  use ExUnit.CaseTemplate

  using do
    quote do
      use Connect4Web.ConnCase
      import unquote(__MODULE__)
      ExUnit.Case.register_attribute(__MODULE__, :platform)

      setup :set_platform_from_context
    end
  end

  def set_platform_from_context(ctx) do
    if platform = ctx.registered[:platform] do
      {:ok,
       conn:
         Phoenix.LiveViewTest.put_connect_params(ctx.conn, %{
           "_platform" => Atom.to_string(platform)
         })}
    else
      :ok
    end
  end
 end
 ```
 
 This lets us set the platform for the test using test attrs.
 
 ```elixir
   @platform :swiftui
  test "connected mount", %{conn: conn} do
    {:ok, _view, html} = live(conn, "/")

    assert html =~ "Connect4"
  end
 ```
 
@bcardarella mentioned he wants to wait to merge this in until we've gotten to play with it in the wild. I can hold off on a PR until we're more confident in the pattern.

**Comment by bcardarella** [comment]
we may want to expand this for:

```elixir
@platform :swiftui
@target :watchos
```

but we need to do some more discovery to see if Jetpack has a similar matrix and if we even use the proposed API changes in #28

**Comment by BrooklinJazz** [comment]
Taking note of one possible issue with my solution above.

Using [put_connect_params](https://hexdocs.pm/phoenix_live_view/Phoenix.LiveViewTest.html#put_connect_params/2) makes it possible for the user to override the connect params in their test.

I encountered this issue when trying to use the connect params to provide the pid of a process.

Session seems to be the preferred approach https://elixirforum.com/t/fundamentals-of-passing-data-from-the-plug-connection-to-the-liveview/31788 so this might be a non-issue.

We could avoid the problem by using [Plug.Conn.put_private/3](https://hexdocs.pm/plug/Plug.Conn.html#put_private/3) instead. However, this would require a change on the LVN side to allow our own private connection field to override the platform in `LiveViewNative.Session`.

**Comment by bcardarella** [comment]
@BrooklinJazz are you asking if we can lock down `conn` to prevent mutation of the LVN values? If so then that won't be possible, with any DSL we have to expect that somebody may draw outside the lines

**Comment by BrooklinJazz** [comment]
No not that we can lock it down.

Currently we use connected params to store/access the platform id. The connected params use a specific private conn field.

I'm suggesting if we want to let devs set the platform in a test we instead use our own private conn field rather than using the same field as connected params.

Reading the docs using a private field prefaced by the library name seemed to be recommended.

**Comment by bcardarella** [comment]
but that would deviate from how we are consuming and evaluating that value in the application itself, no?

**Comment by BrooklinJazz** [comment]
Hmm, you're right.

I think this is a non-issue then.

**Comment by bcardarella** [comment]
I think that we'll have a few paths on testing:

1. making use of the pre-existing Phoenix style with the mocked headless browser. This is likely the same way to go for us.
2. Carson is working on an integration testing branch for the client, this will spawn a simulator and allow for assertions on the rendering. This is really intended for the framework so that we can suss out any breaking changes that sneak into the lib but maybe it can be repurposed for app development?

**Comment by AZholtkevych** [comment]
@BrooklinJazz should I close this one? Thank you

**Comment by BrooklinJazz** [comment]
It's not resolved, and I think Brian mentioned it serving as an epic for any testing work we do in LVN.

I understand wanting to close it since it's on the backburner right now, but I think we should keep it open unless other folks want to close it

**Comment by AZholtkevych** [comment]
Sure thing, thanks a lot

**Comment by bcardarella** [comment]
I spent some time in December looking into this. The current ClientProxy in LiveViewTest is an issue for us to do proper testing because the markup marsing mutates tagname and attribute casing. (downcases everything)

I will look into providing our own client proxy for v0.5 or later. It's going to be a very heavy lift if we cannot find performance parser that preserves casing.

**Comment by bcardarella** [comment]
Closed with https://github.com/liveview-native/live_view_native/pull/210
