### ISSUE TITLE
Rethinking the target pattern to match on function definitions

### ISSUE THREAD

**Issue by bcardarella** [liveview-native/live_view_native#28]
See: https://github.com/liveview-native/elixirconf_chess/blob/main/lib/elixirconf_chess_web/live/index_live.ex#L12

example:

```elixir
def render(%{ platform_id: :swiftui, native: %{ platform_config: %{ user_interface_idiom: "watch" } } } = assigns) do
```

While something this complex may be technically correct, it is not meeting our standard of being something easy to use. We should simply have:

```elixir
 def render(%{ platform_id: :swiftui, target_id: :watchos}  = assigns) do
```

Any reason why this isn't a good idea?

**Comment by bcardarella** [comment]
btw, I'm of the mind dropping the `_id` and just have:

```elixir
def render(%{ platform: :swiftui, target: :watchos}  = assigns) do
```

If there is a concern about any collision of names we can nest under `native`:

```eliixr
def render(%{ native: %{platform: :swiftui, target: :watchos}}  = assigns) do
```

**Comment by bcardarella** [comment]
I believe we should be emitting this from the client rather than converting in Elixir. As we expand into jetpack we need to normalize the schema.

**Comment by supernintendo** [comment]
Fixed by https://github.com/liveview-native/live_view_native/pull/60
