### ISSUE TITLE
VStack  is used in WebUI

### ISSUE THREAD

**Issue by dbii** [liveview-native/live_view_native#42]
In the WebUI version for Render Patterns -> Function Components the WebUI version uses <VStack> which is the SwiftUI syntax.  https://github.com/liveview-native/live_view_native/blob/8b98ce11fe17de609e480c8b7126367896053937/guides/common-features/render-patterns.md?plain=1#L64-L72

Probably should be something like

```
    ~H"""
     <div class="flex w-full h-screen items-center">
       <img src="my-logo.png" />
       <h1><%= @title %></h1>
     </div>
     """
```

**Comment by dbii** [comment]
I can make a PR if you want that to be the solution.

**Comment by bcardarella** [comment]
Fixed in https://github.com/liveview-native/live_view_native/pull/43
