### ISSUE TITLE
Add classname safelist

### ISSUE THREAD

**Issue by supernintendo** [liveview-native/live_view_native#74]
Add the ability to define a safelist for class names, similar to how it works in [Tailwind](https://tailwindcss.com/docs/content-configuration#safelisting-classes). Safelisted class names should always be included in the list of class names passed to stylesheet compilation, regardless of whether they're detected when tree shaking class names.

**Comment by carson-katri** [comment]
Another option that keeps all classes with zero arguments would be helpful too. Then you wouldn't have to list them at all.

**Comment by AZholtkevych** [comment]
Rejecting, according to @bcardarella
