### ISSUE TITLE
No Feedback for Invalid Elements

### ISSUE THREAD

**Issue by BrooklinJazz** [liveview-native/live_view_native#76]
It would be useful to provide a warning or error when a View is invalid, or when providing a View an attribute that doesn't exist (perhaps even suggesting attributes that do exist).

For example the following Swift Template provides no warning or error.

```
~SWIFTUI"""
<SomeInvalidThing/>
"""
```

If a view is valid, but has invalid attributes that would be useful to provide feedback for aswell.

```
~SWIFTUI"""
<Toggle isOn={true}/>
"""
```

This might warn with something like `"isOn" is an invalid attribute, did you mean "is-on"?`

**Comment by AZholtkevych** [comment]
Rejecting for now, according to @bcardarella . @BrooklinJazz FYI
